### ISSUE TITLE
"Permission Denied" when trying to retrieve list of drives from connected device.

### ISSUE THREAD

**Issue by labtec901** [spektor56/OpenpilotToolkit#1]
I am able to connect to my comma device using the program, and list *some* of my drives, but while in the process of listing my drives, the program errors out with that message.  Please let me know if there is any other information that would be useful that I am neglecting.

Log output:

```2021-09-20 16:35:58.838 -07:00 [INF] Found device at address: 192.168.0.104
2021-09-20 16:35:58.844 -07:00 [INF] Connected to 192.168.0.104 on port 8022
2021-09-20 16:35:59.201 -07:00 [INF] Connected to Comma device at 192.168.0.104 on port 8022
2021-09-20 16:36:04.522 -07:00 [ERR] Error retrieving drive
Renci.SshNet.Common.SftpPermissionDeniedException: Permission denied
   at Renci.SshNet.Sftp.SftpSession.RequestOpenDir(String path, Boolean nullOnError)
   at Renci.SshNet.SftpClient.InternalListDirectory(String path, Action`1 listCallback)
   at OpenpilotSdk.Sftp.Extensions.GetFiles(SftpClient client, String directory)+MoveNext() in C:\Users\l-bre\source\repos\OpenpilotToolkit\OpenpilotSdk\Sftp\Extensions.cs:line 37
   at OpenpilotSdk.Hardware.Comma2.GetSegment(DateTime driveDate, Int32 index) in C:\Users\l-bre\source\repos\OpenpilotToolkit\OpenpilotSdk\Hardware\Comma2.cs:line 299
   at OpenpilotSdk.Hardware.Comma2.GetDrives()+MoveNext() in C:\Users\l-bre\source\repos\OpenpilotToolkit\OpenpilotSdk\Hardware\Comma2.cs:line 434
   at OpenpilotToolkit.OpenpilotToolkitForm.<>c__DisplayClass13_0.<lbCommaList_SelectedIndexChanged>b__0() in C:\Users\l-bre\source\repos\OpenpilotToolkit\OpenpilotToolkit\OpenpilotToolkitForm.cs:line 261
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at OpenpilotToolkit.OpenpilotToolkitForm.lbCommaList_SelectedIndexChanged(Object sender, EventArgs e) in C:\Users\l-bre\source\repos\OpenpilotToolkit\OpenpilotToolkit\OpenpilotToolkitForm.cs:line 247

**Comment by spektor56** [comment]
looks to be a folder permissions issue, do you have a C2 or a C3?

if you have a C3 looks like same issue as this:
https://github.com/sshnet/SSH.NET/issues/882

**Comment by spektor56** [comment]
funny thing im now also getting this same error even when using winscp, seems like an OP issue

![image](https://user-images.githubusercontent.com/3619794/136638996-eff4b894-f1bd-4bd7-8c82-ee269269faac.png)

**Comment by spektor56** [comment]
I changed the folder to read the drives from as it appears to no longer work with the path that worked in the past, should be fixed in the newest version
