### ISSUE TITLE
Error everytime I try to connect to my Comma3X

### ISSUE THREAD

**Issue by MotormikeTT** [spektor56/OpenpilotToolkit#12]
I a,m currently running SunnyPilot if that matters but everytime I try to connect to the Comma using OPTK, it gives me the following pop-up: 
![image](https://github.com/user-attachments/assets/fe8ce944-0a63-4d5d-9cf5-97ce28f64d82)

The logs show the following:
 ```2024-08-25 00:42:08.250 -04:00 [INF] Connected to 192.168.1.222 on port 8022
2024-08-25 00:42:08.252 -04:00 [INF] Connected to Comma3 device at 192.168.1.222 on port 8022
2024-08-25 00:42:09.022 -04:00 [ERR] Unhandled Exception
System.ArgumentOutOfRangeException: value ('0') must be less than '0'. (Parameter 'value')
Actual value was 0.
   at System.ArgumentOutOfRangeException.ThrowGreaterEqual[T](T value, T other, String paramName)
   at System.ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual[T](T value, T other, String paramName)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at OpenpilotToolkit.OpenpilotToolkitForm.<>c__DisplayClass20_1.<<ScanDevices>b__2>d.MoveNext() in C:\Users\l-bre\source\repos\OpenpilotToolkit\OpenpilotToolkit\OpenpilotToolkitForm.cs:line 414
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```

Any ideas?

**Comment by kayeechow1992** [comment]
Same issue here

**Comment by spectre3ooo** [comment]
Same for me.

**Comment by BigBlock65** [comment]
I had this issue a couple of times. I copied the original zip file contents over the working app directory to fix it.

**Comment by spektor56** [comment]
let me know if it occurs in 1.9.2 or later
