### ISSUE TITLE
Cant see comma 3x

### ISSUE THREAD

**Issue by ps3firebird** [spektor56/OpenpilotToolkit#13]
Software android or windows can't see the comma device,  I can ping it and use putty to access

**Comment by ps3firebird** [comment]
2024-11-10 14:31:32.094 -05:00 [INF] Application Starting.
2024-11-10 14:31:32.388 -05:00 [ERR] Unhandled Exception
System.Exception: Loading FFmpeg libraries ':FFmpeg' failed
   at FlyleafLib.FFmpegEngine..ctor()
   at FlyleafLib.Engine.StartInternalNonUI()
   at FlyleafLib.Engine.StartInternal(EngineConfig config, Boolean async)
   at FlyleafLib.Engine.Start(EngineConfig config)
   at OpenpilotToolkit.OpenpilotToolkitForm.Form1_Load(Object sender, EventArgs e) in C:\Users\l-bre\source\repos\OpenpilotToolkit\OpenpilotToolkit\OpenpilotToolkitForm.cs:line 125
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
2024-11-10 14:31:43.701 -05:00 [INF] Scanning network for devices.
2024-11-10 14:31:43.719 -05:00 [INF] Found network interface: Ethernet 3
2024-11-10 14:31:43.720 -05:00 [INF] Subnet contains more than 1024 addresses, skipping: Ethernet 3.  End Address: 65535
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Ethernet
2024-11-10 14:31:43.720 -05:00 [INF] Network interface is not enabled: Ethernet
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Bluetooth Network Connection
2024-11-10 14:31:43.720 -05:00 [INF] Network interface is not enabled: Bluetooth Network Connection
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Loopback Pseudo-Interface 1
2024-11-10 14:31:43.720 -05:00 [INF] Network interface is not enabled: Loopback Pseudo-Interface 1
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Ethernet-WFP Native MAC Layer LightWeight Filter-0000
2024-11-10 14:31:43.720 -05:00 [INF] Network interface is not enabled: Ethernet-WFP Native MAC Layer LightWeight Filter-0000
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Ethernet-QoS Packet Scheduler-0000
2024-11-10 14:31:43.720 -05:00 [INF] Network interface is not enabled: Ethernet-QoS Packet Scheduler-0000
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Ethernet-WFP 802.3 MAC Layer LightWeight Filter-0000
2024-11-10 14:31:43.720 -05:00 [INF] Network interface is not enabled: Ethernet-WFP 802.3 MAC Layer LightWeight Filter-0000
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Ethernet 3-WFP Native MAC Layer LightWeight Filter-0000
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Ethernet 3-QoS Packet Scheduler-0000
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Ethernet 3-WFP 802.3 MAC Layer LightWeight Filter-0000
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Local Area Connection* 6-WFP Native MAC Layer LightWeight Filter-0000
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Local Area Connection* 6-QoS Packet Scheduler-0000
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Local Area Connection* 7-WFP Native MAC Layer LightWeight Filter-0000
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Local Area Connection* 7-QoS Packet Scheduler-0000
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Local Area Connection* 8-WFP Native MAC Layer LightWeight Filter-0000
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Local Area Connection* 8-QoS Packet Scheduler-0000
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Ethernet (Kernel Debugger)
2024-11-10 14:31:43.720 -05:00 [INF] Network interface is not enabled: Ethernet (Kernel Debugger)
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Local Area Connection* 6
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Local Area Connection* 7
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Local Area Connection* 8
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Ethernet 2
2024-11-10 14:31:43.720 -05:00 [INF] Network interface is not enabled: Ethernet 2
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Local Area Connection* 5
2024-11-10 14:31:43.720 -05:00 [INF] Network interface is not enabled: Local Area Connection* 5
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Local Area Connection* 9
2024-11-10 14:31:43.720 -05:00 [INF] Network interface is not enabled: Local Area Connection* 9
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Wi-Fi
2024-11-10 14:31:43.720 -05:00 [INF] Network interface is not enabled: Wi-Fi
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Teredo Tunneling Pseudo-Interface
2024-11-10 14:31:43.720 -05:00 [INF] Network interface is not enabled: Teredo Tunneling Pseudo-Interface
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Microsoft IP-HTTPS Platform Interface
2024-11-10 14:31:43.720 -05:00 [INF] Network interface is not enabled: Microsoft IP-HTTPS Platform Interface
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: 6to4 Adapter
2024-11-10 14:31:43.720 -05:00 [INF] Network interface is not enabled: 6to4 Adapter
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Local Area Connection* 1
2024-11-10 14:31:43.720 -05:00 [INF] Network interface is not enabled: Local Area Connection* 1
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Local Area Connection* 2
2024-11-10 14:31:43.720 -05:00 [INF] Network interface is not enabled: Local Area Connection* 2
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Local Area Connection* 3
2024-11-10 14:31:43.720 -05:00 [INF] Network interface is not enabled: Local Area Connection* 3
2024-11-10 14:31:43.720 -05:00 [INF] Found network interface: Local Area Connection* 4
2024-11-10 14:31:43.720 -05:00 [INF] Network interface is not enabled: Local Area Connection* 4

**Comment by spektor56** [comment]
I'm guessing it is on this network: 
2024-11-10 14:31:43.719 -05:00 [INF] Found network interface: Ethernet 3
2024-11-10 14:31:43.720 -05:00 [INF] Subnet contains more than 1024 addresses, skipping: Ethernet 3. End Address: 65535

the toolkit currently skips any subnet that has more than 1024 available addresses.

**Comment by victorhooi** [comment]
I'm just downloaded the latest release of OpenPilot Toolkit (version 1.9.2), and run it on a laptop running Windows 11.

My Comma 3X device is connected to the local Wifi network (same one as my laptop), and SSH is enabled, and I already have an existing SSH key added via Github.

I've confirmed both the laptop and Comma 3X device are on the same subnet, they do have connectivity, I can successfully SSH in manually to the Comma 3X device.

However, when I start up OpenPilot Toolkit, it seems to scan, but can't seem to detect the Comma 3X device.

I've uploaded the OpenPilot Toolkit logs to a gist here, in case that helps.

https://gist.github.com/victorhooi/43eb5168266720ee2948509550f54821

Q1 - Do you have any idea why it's not seeing my Comma 3X device?

Q2 - There's also no place to manually enter in an IP address, at least that I can see?

Q3 - Is the OpenPilot Toolkit version shown in the UI somewhere? I was looking, and couldn't for the life of me find it anywhere.

**Comment by hiroo916** [comment]
I'm also looking for a way to manually enter an IP address.

OP workbench (different tool with some similar functions) also couldn't find the comma device on a scan, but allows you to enter a IP address manually and then it found it immediately.

**Comment by spektor56** [comment]
> I'm just downloaded the latest release of OpenPilot Toolkit (version 1.9.2), and run it on a laptop running Windows 11.
> 
> My Comma 3X device is connected to the local Wifi network (same one as my laptop), and SSH is enabled, and I already have an existing SSH key added via Github.
> 
> I've confirmed both the laptop and Comma 3X device are on the same subnet, they do have connectivity, I can successfully SSH in manually to the Comma 3X device.
> 
> However, when I start up OpenPilot Toolkit, it seems to scan, but can't seem to detect the Comma 3X device.
> 
> I've uploaded the OpenPilot Toolkit logs to a gist here, in case that helps.
> 
> https://gist.github.com/victorhooi/43eb5168266720ee2948509550f54821
> 
> Q1 - Do you have any idea why it's not seeing my Comma 3X device?
> 
> Q2 - There's also no place to manually enter in an IP address, at least that I can see?
> 
> Q3 - Is the OpenPilot Toolkit version shown in the UI somewhere? I was looking, and couldn't for the life of me find it anywhere.

are you running something newer than release3 (0.9.7)?  They dropped support for SSH on port 8022 for the C3 on latest master, I published a new version 1.9.3 that will work on port 22 now.

Also, is the IP of your device in this range? because this is where it's looking:  [INF] Scanning IP range: 10.5.1.1 - 10.5.1.255
